Non-null filtering, because sometimes insn's are null and transformer…
narumii/Deobfuscator pull request #76
Opened 2024-08-24 19:42 UTC by Animowany

… catches error.

2024-08-24 19:54 UTC, EpicPlayerA10 requested changes
If instruction is null then some transformer is badly designed. But if you really want i've requested some small changes.

2024-08-24 19:54 UTC, EpicPlayerA10 commented on deobfuscator-transformers/src/main/java/uwu/narumi/deobfuscator/core/other/impl/universal/number/CompareInstructionsTransformer.java
> +            .filter(Objects::nonNull)
You don't need to check here if it is null as you already check it in `FramedInstructionsTransformer`

2024-08-24 19:54 UTC, EpicPlayerA10 commented on deobfuscator-transformers/src/main/java/uwu/narumi/deobfuscator/core/other/impl/universal/number/MathOperationsTransformer.java
> +            .filter(Objects::nonNull)
same here

2024-08-24 19:54 UTC, EpicPlayerA10 commented on deobfuscator-transformers/src/main/java/uwu/narumi/deobfuscator/core/other/impl/universal/number/NumberCastsTransformer.java
> +            .filter(Objects::nonNull)
same here

2024-08-24 19:59 UTC, EpicPlayerA10 commented
And for future reference, don't commit from a master branch, but create a new fresh branch for your PR. This will make it easier for you in your future PRs to any open-source repository.

2024-08-24 20:27 UTC, Animowany commented
You wrote universalnumbertransformer, and i occured many nullpointers, so just inserted a check and now everything is fine.

2024-08-24 20:39 UTC, Animowany commented
> > You wrote universalnumbertransformer, and i occured many nullpointers, so just inserted a check and now everything is fine.
> 
> Hmm. That's unexpected behaviour. Maybe i do some sanity checks after each transformer if any transformer didn't accidentally break.

im now deobfuscating pretty heavily obfuscated jar, so maybe it has some  as null presented insn's if its even possible

2024-08-24 21:04 UTC, EpicPlayerA10 commented
> > > You wrote universalnumbertransformer, and i occured many nullpointers, so just inserted a check and now everything is fine.
> > 
> > 
> > Hmm. That's unexpected behaviour. Maybe i do some sanity checks after each transformer if any transformer didn't accidentally break.
> 
> im now deobfuscating pretty heavily obfuscated jar, so maybe it has some as null presented insn's if its even possible

If jar is valid and it is running well, then there shouldn't be any null instructions. Some transformer might broke it.

2024-08-24 23:36 UTC, Janmm14 commented
i neverhad to check an instruction being null

2024-08-25 08:34 UTC, narumii commented
> > > > You wrote universalnumbertransformer, and i occured many nullpointers, so just inserted a check and now everything is fine.
> > > 
> > > 
> > > Hmm. That's unexpected behaviour. Maybe i do some sanity checks after each transformer if any transformer didn't accidentally break.
> > 
> > 
> > im now deobfuscating pretty heavily obfuscated jar, so maybe it has some as null presented insn's if its even possible
> 
> If jar is valid and it is running well, then there shouldn't be any null instructions. Some transformer might broke it.

Perhaps better solution would be attaching the jar in question as a test suite?
Null insn should not happen, but at this point i would not be suprised since it is asm.

2024-08-25 08:34 UTC, closed without merging

2024-09-10 14:14 UTC, EpicPlayerA10 commented
@Animowany Your issue should be partially resolved by https://github.com/narumii/Deobfuscator/commit/521c096282f43fdfff1b069d7f8f156ee4fc5ff9 . Now the deobfuscator will throw an error which transformer did something bad in instructions list, instead of acting this weird behaviour with replacing all instructions with nulls. By this change you can then find the root cause of an error very easily.